# Generated by Django 5.2.1 on 2025-06-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_type',
            field=models.CharField(choices=[('male', 'Male Artist'), ('female', 'Female Artist'), ('band', 'Band'), ('assortment', 'Assortment'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
