# Generated by Django 5.2.1 on 2025-06-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0002_artist_artist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrecord',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
