# Generated by Django 5.2.1 on 2025-06-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0003_change_price_to_integer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VinylImage',
        ),
    ]
