# Generated by Django 5.2.1 on 2025-06-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0004_remove_vinyl_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinylrecord',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='vinylrecord',
            name='catalog_number',
        ),
        migrations.RemoveField(
            model_name='vinylrecord',
            name='pressing_year',
        ),
    ]
