# Generated by Django 5.2.1 on 2025-06-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_featured_vinyl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
