# Generated by Django 5.2.1 on 2025-06-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='helpful_votes',
            new_name='helpful_count',
        ),
        migrations.AddField(
            model_name='reviewhelpful',
            name='is_helpful',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reviewhelpful',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review'),
        ),
    ]
