# Generated by Django 5.2.1 on 2025-06-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_helpful_votes_review_helpful_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='helpful_count',
        ),
        migrations.DeleteModel(
            name='ReviewHelpful',
        ),
    ]
